application: qtpytictactoe
version: 1
runtime: python
api_version: 1

handlers:

# Script

# The bot's handler
- url: /getmove
  script: getmove.py

# Static

# Game page
- url: /
  static_files: static/index.html
  upload: static/index.html
# Cache manifest
- url: /qtpy.manifest
  static_files: static/qtpy.manifest
  upload: static/qtpy.manifest
  mime_type: text/cache-manifest
# Javascript and images
- url: /((.*)\.(js|css|png|gif|ico))
  static_files: static/\1
  upload: static/(.*\.(js|css|png|gif|ico))

# DEBUG

- url: /debug
  static_files: static/debug.html
  upload: static/debug.html
skip_files:
- ^static/debug\.html